### ISSUE TITLE
Lock/Unlock wallet generates new redundant wallets

### ISSUE THREAD

**Issue by retotrinkler** [Trinkler/imagewallet.io#43]
Please provide the following information:

![image](https://user-images.githubusercontent.com/13721565/51339546-01895880-1a8d-11e9-896a-7d6f558c8b21.png)

### Expected behaviour

No new wallets generated

### Actual behaviour

3 new wallets generated on each `Lock Wallet`, `Unlock Wallet` clicks

### Information about our environment

* OS & Verison
* Browser & Version
* Parity version
* ... other helpful information

**Comment by retotrinkler** [comment]
closing as dublicate

**Comment by takahser** [comment]
https://github.com/Trinkler/imagewallet.io/issues/46
